# This configuration is intended for development purpose, have to harden it for production
name: oracle
services:
  redis:
    image: redis:7.2.3
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379
