@base=http://localhost:8080

###
PUT {{base}}/oracle/var
Content-Type: application/json

{
  "portfolioValue": 15000.00,
  "assets": [
    {
      "ticker": "AAPL",
      "value": 15000.00
    }
  ]
}
